title: Kat Chen
description: NYC-based journalist and illustrator
url: "https://www.cntraveler.com/contributor/kat-chen"
Instagram: "https://www.instagram.com/animatikat/?hl=en"
logo: /assets/headshot_kc_circle.png
theme: jekyll-theme-minimal 
